/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qin_study_HelloJNI */

#ifndef _Included_com_qin_study_HelloJNI
#define _Included_com_qin_study_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qin_study_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qin_study_HelloJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_qin_study_HelloJNI
 * Method:    SetVolumeLevel
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qin_study_HelloJNI_SetVolumeLevel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
